### ISSUE TITLE
Performance bottleneck because of Zetta API

### ISSUE THREAD

**Issue by apehex** [forta-network/bot-alert-rate#5]
hi @mwakaba2 !
I used your utility in my bot, it was very practical :)
The problem is the time it takes to query the Zetta API: around 50-100ms / transaction.
This (+ my bot inefficiency :D ) caused some transactions to drop.
Would it be worth to implement a variation of this package to compute the alert rate locally?

**Comment by mwakaba2** [comment]
@apehex new version is out 🎉 - https://pypi.org/project/bot-alert-rate/0.0.5/
